site_name: weedtrack
site_description: Tracking your weed made easy
repo_url: https://github.com/peauc/weedtrackapi
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/peauc">peauc</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
