# Generated by Django 3.0.3 on 2020-04-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strain_stock', '0002_strainoperation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strainstock',
            old_name='strainName',
            new_name='strain_name',
        ),
    ]
