# Generated by Django 3.0.3 on 2020-04-18 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('strain_stock', '0004_strainoperation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='strainstock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
